version: '3'

volumes:
  data_dev: {}

services:
  {{ cookiecutter.project_slug }}:
    build:
      context: .
      dockerfile: ./compose/{{ cookiecutter.project_slug }}/Dockerfile-dev
    environment:
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8
      - ENVTYPE=dev
    #env-file:
    #  - ./.envs/.dev/.{{ cookiecutter.project_slug }}
    image: {{ cookiecutter.project_slug }}:dev
    volumes:
      - .:/app
      - data_dev:/data
    #command: /start
