version: '3'

volumes:
  data: {}

services:
  {{ cookiecutter.project_slug }}:
    build:
      context: .
      dockerfile: ./compose/{{ cookiecutter.project_slug }}/Dockerfile
    environment:
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8
    #env-file:
    #  - ./.envs/.production/.{{ cookiecutter.project_slug }}
    image: {{ cookiecutter.project_slug }}
    volumes:
      - .:/app
      - data:/data
    #command: /start
